# Generated by Django 4.1.1 on 2022-09-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Модель машины')),
                ('engine', models.CharField(max_length=60)),
                ('hp', models.IntegerField(null=True)),
                ('nm', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='model_img')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_series', models.CharField(max_length=40, unique=True)),
                ('engine_series', models.CharField(max_length=60)),
                ('hp_series', models.IntegerField(null=True)),
                ('nm_series', models.IntegerField(null=True)),
                ('image_series', models.ImageField(blank=True, null=True, upload_to='model_series_img')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.model')),
            ],
        ),
    ]
