# Generated by Django 4.1.1 on 2022-09-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='model_car',
            new_name='model',
        ),
    ]
