# Generated by Django 4.1.1 on 2022-09-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_rename_model_car_series_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='image_series',
        ),
    ]
