# Generated by Django 4.1.1 on 2022-09-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_series_image_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_series',
            field=models.ImageField(blank=True, null=True, upload_to='model_series_img'),
        ),
    ]
